### ISSUE TITLE
[FEAT] 댓글 텍스트필드 구현

### ISSUE THREAD

**Issue by seunggyun-jeong** [2022OSS-Dev-Competition-ENG-Project/ENG-iOS-APP#31]
## 📌  Feature Issue
댓글 텍스트 필드 구현

## 📝  To-do
- [x] 댓글 텍스트 필드 UI 구현
- [x] 댓글 텍스트 필드 Sticky화
- [x] 댓글 작성 기능 구현

**Comment by seunggyun-jeong** [comment]
## 모든 기능 구현 완료
- Related : #30
